import { randomBytes } from 'node:crypto';

export type SupportType = 'complaint' | 'support_request';

export interface BuildSupportEmailInput {
  type: SupportType;
  name: string;
  email: string | null;
  phone: string | null;
  details: string;
  /** Reference id, e.g. SUP-20260709-AB12CD. Generated by the caller. */
  reference: string;
  /** Base URL of the serving sub-domain; omitted from the subject when unset. */
  linkBaseUrl?: string;
  /** Display name for the "Team <name>" sign-off. */
  teamName: string;
  /** ISO-8601 timestamp, stamped by the caller. */
  submittedAt: string;
}

export interface SupportEmail {
  subject: string;
  html: string;
}

const TYPE_LABELS: Record<SupportType, string> = {
  complaint: 'Complaint',
  support_request: 'Support Request',
};

// Crockford-style base32 alphabet (no 0/1/O/I ambiguity) for readable refs.
const REFERENCE_ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
const REFERENCE_LENGTH = 6;

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Collapse any CR/LF/tabs to single spaces so they can't break an email header. */
function oneLine(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

/**
 * Generate a support reference of the form `SUP-YYYYMMDD-XXXXXX`, where the
 * date is UTC and the suffix is 6 crypto-random base32 characters. Pure apart
 * from the crypto RNG, so it is directly unit-testable (shape / date).
 */
export function generateSupportReference(now: Date): string {
  const yyyy = now.getUTCFullYear().toString().padStart(4, '0');
  const mm = (now.getUTCMonth() + 1).toString().padStart(2, '0');
  const dd = now.getUTCDate().toString().padStart(2, '0');

  const bytes = randomBytes(REFERENCE_LENGTH);
  let suffix = '';
  for (let i = 0; i < REFERENCE_LENGTH; i += 1) {
    suffix += REFERENCE_ALPHABET[bytes[i] % REFERENCE_ALPHABET.length];
  }

  return `SUP-${yyyy}${mm}${dd}-${suffix}`;
}

/**
 * Builds the support notification email from the submitted contact form. Pure:
 * the caller supplies the reference, timestamp and resolved fields. All
 * user-controlled strings are HTML-escaped in the body; the subject is
 * flattened to a single line so it can't inject email headers.
 */
export function buildSupportEmail(input: BuildSupportEmailInput): SupportEmail {
  const { type, name, email, phone, details, reference, teamName, submittedAt } = input;
  const typeLabel = TYPE_LABELS[type];
  const link = input.linkBaseUrl ?? '';

  const subject = oneLine(
    `Issue Number: ${reference} — ${typeLabel} from ${name}` +
      (link ? ` from ${link}` : '')
  );

  const emailText = email ?? '—';
  const phoneText = phone ?? '—';

  const rows: Array<[string, string]> = [
    ['Reference', reference],
    ['Name', name],
    ['Phone', phoneText],
    ['Email', emailText],
    ['Submitted at', submittedAt],
    ['Consent to share contact', 'Yes'],
  ];
  const detailRows = rows
    .map(
      ([label, value]) =>
        `<tr><td style="padding:2px 8px;color:#666">${escapeHtml(label)}</td>` +
        `<td style="padding:2px 8px">${escapeHtml(value)}</td></tr>`
    )
    .join('');

  const html = `<div>
  <p>The below ${escapeHtml(typeLabel)} has been raised by ${escapeHtml(name)}</p>
  <p style="white-space:pre-wrap">${escapeHtml(details)}</p>
  <hr />
  <p style="margin:0 0 4px;font-weight:600">Contact details</p>
  <table style="border-collapse:collapse;font-size:13px">${detailRows}</table>
  <hr />
  <p style="margin:8px 0 0">Regards,<br />Team ${escapeHtml(teamName)}</p>
</div>`;

  return { subject, html };
}
